FROM node:20 AS build
WORKDIR /app
COPY tailwindcss-3.4.10.tgz ./
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20 AS preview
WORKDIR /app
COPY --from=build /app .
EXPOSE 5173
CMD ["npm", "run", "preview", "--", "--host"]


